apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lorehub.fullname" . }}-api
  labels:
    {{- include "lorehub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "lorehub.labels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: api
          image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "lorehub.fullname" . }}-config
          env:
            - name: LORE_JWT_SECRET
              value: {{ .Values.global.loreJwtSecret | quote }}
          ports:
            - containerPort: {{ .Values.api.service.port }}
