apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lorehub.fullname" . }}-web
  labels:
    {{- include "lorehub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: web
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "lorehub.labels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: web
          image: {{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "lorehub.fullname" . }}-config
          ports:
            - containerPort: {{ .Values.web.service.port }}
